services:
  - type: web
    name: cockroachdb-proxy
    runtime: docker
    plan: free
    envVars:
      - key: API_KEY
        sync: false
      - key: COCKROACH_HOST
        sync: false
      - key: COCKROACH_PORT
        value: "26257"
      - key: COCKROACH_USER
        sync: false
      - key: COCKROACH_PASSWORD
        sync: false
      - key: COCKROACH_SSL
        value: require
    healthCheckPath: /health
